### ISSUE TITLE
PyPI hosting - cannot reference installed version in requirements.txt & numpy is not installed as a dependency

### ISSUE THREAD

**Issue by DavidAntliff** [moble/quaternion#117]
First of all, @moble, thank you for this fine library and my apologies if this is a PyPI or pip issue and isn't under your control. If that's the case, please just let me know and I'll see if anyone at PyPI or pip can help.

**Describe the bug**
After installing numpy-quaternion via `pip`, the version installed is (currently) `2019.6.26.0.25.45`. This seems to be very close to my actual local time! If I `pip freeze` I then get:
```
numpy-quaternion==2019.6.26.0.25.45
```
But attempting to install this version fails:

```
$ pip install numpy-quaternion==2019.6.26.0.25.45
Collecting numpy-quaternion==2019.6.26.0.25.45
  ERROR: Could not find a version that satisfies the requirement numpy-quaternion==2019.6.26.0.25.45 (from versions: 2016.8.25.dev221305696, 2016.8.27.dev94615536, 2016.8.29.dev231774547, 2016.8.29.dev258356679, 2016.8.30.dev40560191, 2016.8.30.dev142425726, 2016.10.12.dev209377407, 2016.10.12.dev268044850, 2016.10.31.dev83815479, 2016.11.30.dev43897183, 2016.11.30.dev51027772, 2016.11.30.dev101697805, 2016.11.30.dev220855819, 2017.1.8.dev232822920, 2017.2.28.dev21024698, 2017.2.28.dev244535353, 2017.3.1.14.16.51.dev141622364, 2017.3.2.17.14.39.dev234032961, 2017.3.10.4.36.28.dev170668370, 2017.3.13.12.4.42.dev87917346, 2017.3.13.14.42.16.dev259768242, 2017.3.13.14.50.58.dev88917002, 2017.3.14.1.52.59.dev139985168, 2017.3.16.21.51.57.dev242408302, 2017.3.29.15.26.47.dev5411921, 2017.4.5.14.49.15.dev261789573, 2017.5.8.13.59.46.dev255649235, 2017.5.23.14.39.48.dev53804477, 2017.5.24.14.5.54.dev33077846, 2017.6.2.13.32.11.dev17910925, 2017.6.5.21.14.57.dev19253288, 2017.6.5.21.19.52.dev20097538, 2017.6.9.12.19.46.dev119623821, 2017.6.28.13.11.35.dev177226304, 2017.7.13.12.9.11.dev31661272, 2017.7.13.12.10.29.dev114912538, 2017.10.4.13.50.36.dev52395737, 2017.10.4.16.20.25.dev180388366, 2017.10.14.11.11.56, 2017.10.14.11.13.13.dev206252663, 2017.10.19.15.47.40, 2017.10.20.10.41.30, 2017.11.26.19.0.13, 2018.2.21.15.41.17, 2018.2.22.22.24.39, 2018.2.24.23.5.39, 2018.3.2.9.28.43, 2018.3.6.20.3.47, 2018.4.16.17.4.9, 2018.4.18.16.15.4, 2018.4.18.16.18.52, 2018.4.26.9.35.2, 2018.5.2.21.39.8, 2018.5.9.12.22.4, 2018.5.9.17.32.22, 2018.5.9.17.41.0, 2018.5.9.20.48.6, 2018.5.9.21.48.54, 2018.5.10.13.50.12, 2018.5.16.9.16.21, 2018.5.17.10.19.59, 2018.5.31.13.56.17, 2018.5.31.16.8.42, 2018.6.18.16.33.12, 2018.7.5.21.55.13, 2018.9.30.22.1.29, 2018.9.30.23.2.27, 2018.10.1.15.1.2, 2018.10.1.15.18.24, 2018.10.1.15.34.19, 2018.10.1.15.39.8, 2018.10.1.15.59.11, 2018.10.1.16.30.46, 2018.10.1.17.6.20, 2018.10.1.22.5.32, 2018.11.3.1.0.41, 2018.11.28.14.6.55, 2018.12.24.11.8.55, 2019.3.18.14.33.20, 2019.5.24.11.54.47, 2019.6.11.17.26.3)
ERROR: No matching distribution found for numpy-quaternion==2019.6.26.0.25.45
```
The last and latest version number in that list (`2019.6.11.17.26.3`) can be specified, but when pip installs it, it actually chooses the current-time version (see log below).

I've never seen this kind of real-time versioning before - is this a PyPI feature or something the numpy-quaternion author has implemented?

Secondly, I wonder if this package's numpy dependency is being handled correctly? I ask because even if `numpy` is specified in `requirements.txt`, even if it's before `numpy-quaternion` (should it even matter?), pip tries to install `numpy-quaternion` first, which then fails as `numpy` isn't installed. I have to manually install `numpy` first as below.

To reproduce (python 3.7.3):
```
# Create requirements.txt for numpy and numpy-quaternion:
$ echo "numpy==1.16.4" > requirements.txt
$ echo "numpy-quaternion==2019.6.11.17.26.3" >> requirements.txt

# Create a venv for isolated demonstration:
$ python -m venv venv
$ . venv/bin/activate

# Attempt to install the required packages:
$ pip install -r requirements.txt 
Collecting numpy-quaternion==2019.6.11.17.26.3 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e3/36/c4a17998ed49b7d2818c82fcfbf2f2726f7ef4cf76c947834a6759f12993/numpy-quaternion-2019.6.11.17.26.3.tar.gz
    Complete output from command python setup.py egg_info:
    The variable 'package_version' was not present in the environment
    Setup.py using strftime version='2019.6.26.0.32.56'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1d9dhrvz/numpy-quaternion/setup.py", line 59, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1d9dhrvz/numpy-quaternion/

# Manually install numpy first
$ pip install numpy==1.16.4

$ pip install -r requirements.txt 
Collecting numpy-quaternion==2019.6.11.17.26.3 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e3/36/c4a17998ed49b7d2818c82fcfbf2f2726f7ef4cf76c947834a6759f12993/numpy-quaternion-2019.6.11.17.26.3.tar.gz
  Requested numpy-quaternion==2019.6.11.17.26.3 from https://files.pythonhosted.org/packages/e3/36/c4a17998ed49b7d2818c82fcfbf2f2726f7ef4cf76c947834a6759f12993/numpy-quaternion-2019.6.11.17.26.3.tar.gz#sha256=d7278ace6928279990897092904e7f5873b333c899b577605b12551bcca4129f (from -r requirements.txt (line 1)), but installing version 2019.6.26.0.33.50
Requirement already satisfied: numpy>=1.13 in ./venv/lib/python3.7/site-packages (from numpy-quaternion==2019.6.11.17.26.3->-r requirements.txt (line 1)) (1.16.4)
Installing collected packages: numpy-quaternion
  Running setup.py install for numpy-quaternion ... done
Successfully installed numpy-quaternion-2019.6.26.0.33.50
```

Note the "but installing version 2019.6.26.0.33.50" above, which is the UTC date and time I ran the command.

**Expected Behaviour**
I would expect to be able to specify the currently installed version of `numpy-quaternion` in my `requirements.txt` file and have that work as a reproducible `pip` installation. I would also expect the presence of `numpy` in `requirements.txt` to ensure that `numpy` is installed before `numpy-quaternion` is, but that does not appear to happen.

**Final words**
Again, I appreciate that this might be a PyPI or even a `pip` issue (and that there may be two separate issues here, too), so as a first port of call I'm approaching you in case you have some insight. If none of this is under your control I will see if I can find an answer elsewhere.

**Comment by moble** [comment]
The behavior you describe is a mistake, and I hadn't encountered it before.  While I also control the pypi/numpy-quaternion project, I don't actually use pip (I much prefer conda, both as a developer and as a user).  But my tests suggest that I've solved this with some of my most recent commits, so try again.

> Secondly, I wonder if this package's numpy dependency is being handled correctly?

See issue #99.
