### ISSUE TITLE
Latest version not installable under Python 2

### ISSUE THREAD

**Issue by bluenote10** [moble/quaternion#135]
Maybe dropping Python 2 support was on purpose, but then the package should have tagged as not having Python 2 support to avoid pip picking up the incompatible version.

Steps to reproduce with a fresh venv:

```sh
$ virtualenv test
$ . test/bin/activate
$ pip install numpy numpy-quaternion
```

Crashes with:

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting numpy
  Downloading numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl (17.0 MB)
     |████████████████████████████████| 17.0 MB 6.7 MB/s 
Collecting numpy-quaternion
  Downloading numpy-quaternion-2020.4.24.9.29.7.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 5.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv_test/test/bin/python2 /tmp/venv_test/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpDF4RDd
         cwd: /tmp/pip-install-EVdMvV/numpy-quaternion
    Complete output (52 lines):
    The variable 'package_version' was not present in the environment
    running dist_info
    creating /tmp/pip-modern-metadata-Gw02vP/numpy_quaternion.egg-info
    writing requirements to /tmp/pip-modern-metadata-Gw02vP/numpy_quaternion.egg-info/requires.txt
    writing /tmp/pip-modern-metadata-Gw02vP/numpy_quaternion.egg-info/PKG-INFO
    writing top-level names to /tmp/pip-modern-metadata-Gw02vP/numpy_quaternion.egg-info/top_level.txt
    writing dependency_links to /tmp/pip-modern-metadata-Gw02vP/numpy_quaternion.egg-info/dependency_links.txt
    writing manifest file '/tmp/pip-modern-metadata-Gw02vP/numpy_quaternion.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 122, in <module>
        setup(**setup_metadata)
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/tmp/venv_test/test/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "setup.py", line 113, in finalize_options
        import builtins
    ImportError: No module named builtins
    ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/venv_test/test/bin/python2 /tmp/venv_test/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpDF4RDd Check the logs for full command output.
```

As a work-around it is possible to pre `pip install future`, but that violates the general practice that all requirements should be installable in a single step, and the installs within that installation should not depend on installation order.

**Comment by moble** [comment]
Nothing in this package has changed recently in any way that should affect python 2 compatibility.  In particular, your error evidently happens because [this line](https://github.com/moble/quaternion/blob/866fdc54ba5a4c2eb2013f3935988578f6080bc1/setup.py#L110) raises an exception for you — which is the expected behavior in python 3, but has always worked in python 2 as far as I'm aware.  I suspect that you're getting this because of some change to the infrastructure — maybe pip itself.

Anyway, I believe the package itself is actually still compatible with python 2, so I won't be marking it for compatibility.  But I don't mind [adding another `except` clause](https://github.com/moble/quaternion/commit/0e02888df8d6e3fc8158335ba18f9defa03212f4) to just skip the attempted fix, and if installation fails for other reasons, I give up completely.

> violates the general practice that all requirements should be installable in a single step, and the installs within that installation should not depend on installation order.

Ironically, the problem you're running into is precisely because python/pip/numpy as currently implemented violates this principle, and I had to hack setup.py to try to get around this problem — as you yourself saw already in issue #99.  As always, I really recommend just using conda for any serious scientific computing.  Pip is explicitly designed for the webby side of python.
