### ISSUE TITLE
pip install error for current version on pypi - 2020.4.29.8.34.20

### ISSUE THREAD

**Issue by 2sn** [moble/quaternion#136]
**Describe the bug**
Can't install current version from pip.

**To Reproduce**
```
pip install -y numpy-quaternion
```

**Expected behavior**
```
Successfully installed numpy-quaternion-2020.4.29.8.34.20
```
**Actual behavior**
```
Collecting numpy-quaternion
  Downloading numpy-quaternion-2020.4.29.8.34.20.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 3.8 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/alex/Python/bin/python3.8 /home/alex/Python/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lanik85r/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'numpy>=1.13'
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/home/alex/Python/lib/python3.8/runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/alex/Python/lib/python3.8/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/alex/Python/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/home/alex/Python/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/home/alex/Python/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/home/alex/Python/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/home/alex/Python/lib/python3.8/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/home/alex/Python/lib/python3.8/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/alex/Python/bin/python3.8 /home/alex/Python/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lanik85r/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'numpy>=1.13' Check the logs for full command output.
```

**Environment (please complete the following information):**
 - Fedora 31
 - Installation method: pip
 - Numpy version: 1.18.3
 - Quaternion version: 2020.4.29.8.34.20

**Additional context**
previous version (2020.4.24.9.29.7) works.
```
pip3 install numpy-quaternion==2020.4.24.9.29.7
```
results in
```
Installing collected packages: numpy-quaternion
Successfully installed numpy-quaternion-2020.4.24.9.29.7
```

**Comment by moble** [comment]
That error isn't coming from this package.  If you look carefully, you see that it actually errors out when it's installing the build dependencies — specifically on this command (the 6th line of your error message):

    [...] pip install [...] setuptools wheel 'numpy>=1.13'

The error itself is actually coming from deep inside `pip`, where it imports from `importlib.resources`, which imports from `typing`, which is what causes the error.

It looks like [there might be a very recent (past few days) change to `pip`](https://github.com/ethereum/eth-abi/issues/131#issuecomment-620981271) that brings this issue up.  In particular, your error is originating in `.../lib/python3.8/site-packages/typing.py`.  For me, in a fresh install of python 3.8, this file doesn't exist; ["in Python 3.5 and later, the typing module lives in the stdlib"](https://pypi.org/project/typing/), and I find it in `.../lib/python3.8/typing.py`.  (Note the missing `site-packages`.)  Apparently, you've somehow installed another `typing` package, and it's reading from that one.

Also, my guess is that your `pip3` command for installing the previous version of this package just points to an older version of `pip`.  Recent installations of `pip` don't include `pip3`, for me.  In fact, my system only finds `pip3` in some old version from my OS, and runs `pip` version 19.0.3, instead of 20.1.  Try `pip --version` and `pip3 --version`, and see what they give you.

The link I pointed to above says that he solved his problem by downgrading to `pip` version 20.0.2.  Otherwise, you might try `pip uninstall typing`.  If that doesn't work, you could try to just move your `site-packages/typing.py` to somewhere off your python sys path.  And if that doesn't work, I'd say you'll need to re-install your python environment.

(And as always, my advice is to use conda instead of pip, because the pypa developers make it quite clear that they want python to work for web developers, but have no interest in supporting scientific python.)

**Comment by 2sn** [comment]
I am using the current version of pip
```
pip --version
pip 20.1 from /home/alex/Python/lib/python3.8/site-packages/pip (python 3.8)
```
uninstalling `typing`
```
pip uninstall typing
Found existing installation: typing 3.7.4.1
Uninstalling typing-3.7.4.1:
  Would remove:
    /home/alex/Python_3.8.2/lib/python3.8/site-packages/typing-3.7.4.1.dist-info/*
    /home/alex/Python_3.8.2/lib/python3.8/site-packages/typing.py
Proceed (y/n)? y
  Successfully uninstalled typing-3.7.4.1
```
does solve the install issue
```
>pip install -U numpy-quaternion
Collecting numpy-quaternion
  Downloading numpy-quaternion-2020.5.1.9.54.41.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 1.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: numpy>=1.13 in ./Python_3.8.2/lib/python3.8/site-packages (from numpy-quaternion) (1.18.3)
Building wheels for collected packages: numpy-quaternion
  Building wheel for numpy-quaternion (PEP 517) ... done
  Created wheel for numpy-quaternion: filename=numpy_quaternion-2020.5.1.9.54.41-cp38-cp38-linux_x86_64.whl size=197162 sha256=6fd8d5231063ee9aa21d6dc8968e098bda06ca17fce2d11bd4193a40dc3ae3c1
  Stored in directory: /home/alex/.cache/pip/wheels/54/74/84/bb03e930e6801c0a28a4f643900af78d4f94665371a9de7c0f
Successfully built numpy-quaternion
Installing collected packages: numpy-quaternion
  Attempting uninstall: numpy-quaternion
    Found existing installation: numpy-quaternion 2020.4.24.9.29.7
    Uninstalling numpy-quaternion-2020.4.24.9.29.7:
      Successfully uninstalled numpy-quaternion-2020.4.24.9.29.7
Successfully installed numpy-quaternion-2020.5.1.9.54.41
```

Thanks a lot for the quick reply.
