### ISSUE TITLE
can't install with pip

### ISSUE THREAD

**Issue by davideCremona** [moble/quaternion#144]
numpy-quaternion non installable via pip3

**To Reproduce**
`sudo pip3 install numpy-quaternion`

**Expected behavior**
numpy-quaternion successfully installs

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation method: pip
 - Numpy version: 1.19.1
 - Quaternion version: 2020.5.19.15.27.24

**Additional context**
Error received:
```
Collecting numpy-quaternion
  Downloading numpy-quaternion-2020.5.19.15.27.24.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 2.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /home/davidecremona/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmphl8dqgf5
         cwd: /tmp/pip-install-7x64tk0k/numpy-quaternion
    Complete output (48 lines):
    The variable 'package_version' was not present in the environment
    running dist_info
    creating /tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.egg-info
    writing /tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.egg-info/requires.txt
    writing top-level names to /tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file '/tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.egg-info/SOURCES.txt'
    creating '/tmp/pip-modern-metadata-j2uayirs/numpy_quaternion.dist-info'
    Traceback (most recent call last):
      File "/home/davidecremona/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/davidecremona/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/davidecremona/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 254, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 126, in <module>
        setup(**setup_metadata)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/_distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/command/dist_info.py", line 35, in run
        bdist_wheel = self.get_finalized_command('bdist_wheel')
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/_distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 858, in get_command_obj
        klass = self.get_command_class(command)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/setuptools/dist.py", line 741, in get_command_class
        ep.require(installer=self.fetch_build_egg)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2469, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/home/davidecremona/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (packaging 19.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('packaging>=20.2'))
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/davidecremona/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmphl8dqgf5 Check the logs for full command output.

```

**Comment by moble** [comment]
That error isn't actually coming from this package.  It's coming from your python installation being unable to solve a very basic dependency issue (the `VersionConflict` about `packaging` in your error message).  Basically, you're using the wrong python.  This isn't really your fault; it's an unfortunate effect of how python works and how they fail to explain how you should actually be using python.  Here are some essential rules for working with python (not just this package):

1. You should basically never use `sudo` to do anything involving python.  Getting permission errors on python commands is usually a sign that you're trying to change something that your OS relies on, which means you could be breaking your OS if you force it.
2. You shouldn't use your OS's python — it's basically just for the OS to use.  You really should use some environment manager with a separate python.  I recommend [`conda`](https://www.anaconda.com/products/individual), but there's a forest of others like `virtualenv`.
3. You almost definitely don't want to use `pip3`.  This may be accidentally picking up the wrong version of python.  Package managers are dropping support (not installing) `pip3`, which means if you call it, your OS may be finding some old version tucked away somewhere that installs to some old python you don't actually want to use.  Just use `pip`, and try to make sure the `pip` command is using the right version of python.  In fact, it's probably better to call it with `python -m pip`, rather than just `pip`.  I'm changing the README to suggest this approach.

So to solve this problem, I recommend just installing conda and then running `conda install -c conda-forge quaternion` — though you could also create your own virtual environment and use pip to install inside of that.

**Comment by moble** [comment]
Also, a fresh `docker run -i -t ubuntu:18.04 bash` followed by

```bash
apt-get update
apt install -y python3-pip
pip3 install numpy-quaternion
```

works correctly (even though I would only install without an environment in a container I'm about to throw away).  This suggests even more strongly that the issue must be something very specific to your installation — possibly caused by past installations as root.

**Comment by davideCremona** [comment]
Thank you, at least I've learned that the system must be fixed :)
