### ISSUE TITLE
numpy and numpy-quaternion  cannot be installed successfully at the same time

### ISSUE THREAD

**Issue by wonderbeyond** [moble/quaternion#55]
`pip install numpy numpy-quaternion` always fails. So we must firstly install *numpy* separately, then install numpy-quaternion.

The [setup.py#L25](https://github.com/moble/quaternion/blob/master/setup.py#L25) of *numpy-quaternion* requires *numpy*, but at installation time *numpy* is not available.

```
$ mkvirtualenv py2 --python=`which python2`

$ pip -V
pip 9.0.1 from /home/wonder/PyEnvs/py2/local/lib/python2.7/site-packages (python 2.7)

$ pip install --no-cache-dir numpy numpy-quaternion
Collecting numpy
  Downloading https://mirrors.aliyun.com/pypi/packages/dd/b5/47bd2174dbb14e5fa2dd6ad28fd1d54d38e84d29c1b131a00354ddb0cae0/numpy-1.13.0-cp27-cp27mu-manylinux1_x86_64.whl (16.6MB)
    100% |████████████████████████████████| 16.6MB 1.1MB/s 
Collecting numpy-quaternion
  Downloading https://mirrors.aliyun.com/pypi/packages/f0/99/f38033e0a90674a7e8a1df5e98d2aa73e73cec8b11955c2ae155d1da9369/numpy-quaternion-2017.06.28.13.11.35.dev177226304.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5TY7nL/numpy-quaternion/setup.py", line 25, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5TY7nL/numpy-quaternion/
```

**Comment by moble** [comment]
Repeat of issue #42.  The workaround is to do
```bash
pip install numpy
pip install numpy-quaternion
```
Patches are welcome.
