### ISSUE TITLE
using quaternions in numba

### ISSUE THREAD

**Issue by ulijh** [moble/quaternion#63]
Hi, currently it doesn't seem possible to use quaternions inside numba compiled methods:

```
import quaternion
import numpy as np
import numba

@numba.njit
def nb_qmult(q1, q2):
    return q1 * q2

a = quaternion.from_rotation_vector([0, 0, np.pi/3])
b = quaternion.from_rotation_vector([np.pi/3, 0, 0])

nb_qmult(a, b)
```
 fails with a TyperError:
```
...
TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x7f1378bb8c88>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/usr/lib/python3.6/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/usr/lib/python3.6/site-packages/numba/typeinfer.py", line 190, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.6/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/usr/lib/python3.6/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
numba.errors.InternalError: 
[1] During: typing of argument at <ipython-input-43-eb04207d2aa0> (7)
--%<-----------------------------------------------------------------

File "<ipython-input-43-eb04207d2aa0>", line 7

This error may have been caused by the following argument(s):
- argument 0: cannot determine Numba type of <class 'quaternion'>
- argument 1: cannot determine Numba type of <class 'quaternion'>
```
I found the numba_quaternion module inside numpy_quaternion, but no documentation and I don't have enough understanding of numba to make sense of it.

Some advice on how to use this would be appreciated!
Thanks!

**Comment by moble** [comment]
You should search issues before you open a new issue.  See #62 and my response there.

**Comment by ulijh** [comment]
Thanks for the quick reply, I actually missed #62. It seems I have to restructure my code or fall back on rotation matrices for my use case.

**Comment by moble** [comment]
I don't know what your use case is, but the basic message is: you should multiply rotations by each other as quaternions (don't convert to rotation matrices to do that because you will lose numerical accuracy and efficiency), whereas you should feel free to convert to matrices if you need to rotate vectors.
