### ISSUE TITLE
Cannot install on windows using pip

### ISSUE THREAD

**Issue by ilango100** [moble/quaternion#75]
I tried to install numpy-quaternion with pip in windows, but got this error.

```
PS C:\Users\ilang> pip install numpy-quaternion
Collecting numpy-quaternion
  Using cached https://files.pythonhosted.org/packages/9d/bb/684537640470970f8b9923639f45ccd4e99c6499b74ce798383d1cee1a27/numpy-quaternion-2018.4.18.16.18.52.tar.gz
    Complete output from command python setup.py egg_info:
    The variable 'package_version' was not present in the environment
    Traceback (most recent call last):
      File "C:\Users\<user>\AppData\Local\Temp\pip-install-_w_n6b5b\numpy-quaternion\setup.py", line 15, in <module>
        version = check_output("""git log -1 --format=%cd --date=format:'%Y.%-m.%-d.%-H.%-M.%-S'""", shell=use_shell).decode('ascii').rstrip()
    NameError: name 'use_shell' is not defined

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<user>\AppData\Local\Temp\pip-install-_w_n6b5b\numpy-quaternion\setup.py", line 19, in <module>
        version = strftime("%Y.%-m.%-d.%-H.%-M.%-S", gmtime())
    ValueError: Invalid format string

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ilang\AppData\Local\Temp\pip-install-_w_n6b5b\numpy-quaternion\
```

I have git installed. So that is not a problem. I tried to find whl for windows but only linux and mac whls are provided in pypi

**Comment by moble** [comment]
As explained in [the README](), I can't actually support Windows directly except via conda-forge, so you should try installing it like that.  You could also run your command as

    set "package_version=2018.4.18.16.18.52" && pip install numpy-quaternion

I'll try to get the setup script to handle cases like this, but I really can't help much on Windows.  Sorry.  Conda is and will remain the only supported way to install on Windows.
